"""Validation, PII scanning, and the reconciliation table (doc 01 §7)."""
from __future__ import annotations
from pathlib import Path
import re
import pandas as pd

from . import config, schema

# \b anchors keep this from matching a digit run glued to underscores/letters
# (e.g. a "..._1783087815.xlsx" source-file id) while still catching real
# phone numbers, which are always set off by a delimiter (+, space, :, etc.).
_PII_PATTERNS = [re.compile(r"whatsapp:", re.I), re.compile(r"\b\d{7,}\b")]

# Checked AFTER schema.normalize_columns, so these are the canonical names.
_CRITICAL = {
    # Chat_summary was required only by the retired category mapping. The v2
    # platform emits free prose there and nothing in the pipeline reads it, so
    # requiring it would fail a source export for a field we do not use.
    "responses": ["Name", "Timestamp", "City", "Age", "Messages"],
    "meal": ["Name", "Timestamp"],
}
# Accepted sheet names per source. v2 renamed them ('users', 'survey responses');
# the v1 names are kept so archived exports still validate.
_SHEET = {
    "responses": {"users", "mmc bot - responses"},
    "meal": {"survey responses", "mmc-meal"},
}


# Columns that are non-reversible hex digests generated by this pipeline, not
# source text. Hex digits are digits, so a slice will occasionally contain a run
# of 7+ of them and trip the phone-number pattern. Exempting them is safe because
# we generate them; exempting anything else is not. Keep this list closed —
# widening it to a prefix match or a dtype rule would blunt the PII gate.
_HASH_COLUMNS = frozenset({"user_id", "message_id"})


def pii_scan(obj) -> list[dict]:
    """Return violation records for whatsapp:/7+-digit runs. Empty list = clean.

    Skips the columns in `_HASH_COLUMNS` (`user_id`, `message_id`): both are
    non-reversible digests this pipeline computes, and by chance a hex slice can
    contain a 7+-digit run. That is not PII and must not be flagged. Raw Excel
    exports carry neither column, so raw-file scans are unaffected. Also skips
    numeric and boolean dtype columns: they hold metrics, not raw
    phone/`whatsapp:` text, so the scan only covers string/object columns."""
    if isinstance(obj, (str, Path)):
        df = pd.read_excel(obj, header=config.DATA_HEADER_ROW, dtype=str)
    else:
        df = obj
    violations = []
    for col in df.columns:
        if str(col) in _HASH_COLUMNS:
            continue
        # Only string/object columns can hold raw phone numbers or "whatsapp:"
        # runs. Numeric (int/float/bool) columns are legitimate metrics —
        # str()'ing a float routinely produces 7+ consecutive decimal digits
        # (e.g. a ratio like 0.8724100327) that is not PII.
        if pd.api.types.is_numeric_dtype(df[col]) or pd.api.types.is_bool_dtype(df[col]):
            continue
        for val in df[col].astype(str).fillna(""):
            if any(p.search(val) for p in _PII_PATTERNS):
                violations.append({"column": str(col), "value_prefix": val[:12]})
                break  # one hit per column is enough to flag
    return violations


def validate_schema(path, kind: str) -> dict:
    xl = pd.ExcelFile(path)
    names = {str(s).strip().lower() for s in xl.sheet_names}
    if not (names & _SHEET[kind]):
        # tolerate single-sheet test fixtures; only enforce for real exports
        if len(xl.sheet_names) != 1:
            raise ValueError(
                f"expected one of {sorted(_SHEET[kind])} for {kind}, "
                f"got {xl.sheet_names}")
    try:
        # header detected, not assumed — matches the loaders
        df = pd.read_excel(path, header=schema.detect_header_row(path, source=kind))
        df = schema.normalize_columns(df, kind)
    except ValueError:
        # fixture/file too short for the real export's header offset: there is
        # no way the critical columns can be present, so fall through to the
        # missing-columns check below with an empty frame.
        df = pd.DataFrame()
    missing = [c for c in _CRITICAL[kind] if c not in df.columns]
    if missing:
        raise ValueError(f"missing critical columns for {kind}: {missing}")
    ts = df["Timestamp"] if "Timestamp" in df.columns else pd.Series(dtype=object)
    non_null = ts.notna().sum()
    parsed = pd.to_datetime(ts, errors="coerce", utc=True).notna().sum()
    rate = 1.0 if non_null == 0 else parsed / non_null
    return {"rows": len(df), "columns": len(df.columns), "ts_parse_rate": float(rate)}


def reconciliation_table(responses: pd.DataFrame, messages: pd.DataFrame,
                         meal: pd.DataFrame) -> pd.DataFrame:
    n_users = responses["user_id"].nunique()
    n_msgs = len(messages)
    # repeat-asker proxy: users at/above p90 question volume
    q = responses.groupby("user_id")["n_questions"].max()
    p90 = q.quantile(0.90)
    repeat_pct = round(100 * (q >= p90).mean(), 1) if q.notna().any() else "pending"
    rows = [
        ("users", n_users),
        ("records", len(responses)),
        ("messages", n_msgs),
        ("users_with_text", messages["user_id"].nunique()),
        ("meal_responses", len(meal)),
        ("meal_response_rate_pct", round(100 * len(meal) / n_users, 1)),
        ("repeat_askers_pct", repeat_pct),
        ("negative_tone_pct", "pending"),  # from NB3 sentiment
    ]
    return pd.DataFrame(rows, columns=["metric", "value"])


def run_checks(responses, messages, meal) -> list[tuple[str, bool, str]]:
    # Second element is always a plain Python bool (not numpy.bool_) so run_meta
    # stays JSON-serializable when a later task persists it.
    checks = []
    checks.append(("P1_pii_responses", bool(pii_scan(responses) == []), "no whatsapp/phone in responses"))
    checks.append(("P1_pii_messages", bool(pii_scan(messages) == []), "no whatsapp/phone in messages"))
    per_user = messages.groupby("user_id")["n_msgs_user"].first().sum()
    checks.append(("P6_spine_invariant", bool(per_user == len(messages)), f"{per_user} == {len(messages)}"))
    checks.append(("P8_meal_unique", bool(meal["user_id"].is_unique), "one MEAL row per user"))
    return checks


# Share of users that must carry a real cluster. Coverage was 1,198/1,392 = 86%
# at the 2026-07-28 export; the shortfall is structural — users who registered
# and never wrote a message have no document to cluster, and land in the
# cluster_id = -1 bucket by design. The bar sits below today's value with room
# for normal drift, but tight enough to catch a clustering run that silently
# dropped a chunk of the corpus.
CLUSTER_COVERAGE_THRESHOLD = 0.80


def cluster_coverage(dim_user: pd.DataFrame) -> float:
    """Share of users carrying a real cluster (not -1, not null).

    NOT a `run_checks` entry: `run_checks` runs inside `load_sami`, before any
    clustering has happened, so a cluster gate cannot live there. `run_pipeline`
    calls this after dim_user is built and surfaces it in parity_check.
    """
    if "cluster_id" not in dim_user.columns or dim_user.empty:
        return 0.0
    cid = pd.to_numeric(dim_user["cluster_id"], errors="coerce")
    return float((cid.notna() & (cid != -1)).mean())
