"""Validation, PII scanning, and the reconciliation table (doc 01 §7)."""
from __future__ import annotations
from pathlib import Path
import re
import pandas as pd

from . import config, schema, taxonomy

# \b anchors keep this from matching a digit run glued to underscores/letters
# (e.g. a "..._1783087815.xlsx" source-file id) while still catching real
# phone numbers, which are always set off by a delimiter (+, space, :, etc.).
_PII_PATTERNS = [re.compile(r"whatsapp:", re.I), re.compile(r"\b\d{7,}\b")]

# From July 2026 the v2 platform emits a timestamped prose summary instead of
# the short taxonomy label v1 emitted ("[2026-07-24 14:15] El usuario preguntó
# sobre..."). taxonomy.normalize_category is an exact-match lookup, so prose
# becomes 'unclassified' — which is the ACCEPTED outcome: those records, and all
# future ones, land in the 'Suggestion' bucket alongside the records that never
# carried a category (checkpoint 2026-07-28). P9 therefore gates on the
# label-shaped summaries only; see labelled_unmappable_share.
_SUMMARY_PROSE = re.compile(r"^\s*\[\d{4}-\d{2}-\d{2}")
SUMMARY_PROSE_THRESHOLD = 0.05

# Checked AFTER schema.normalize_columns, so these are the canonical names.
_CRITICAL = {
    # Chat_summary was required only by the retired category mapping. The v2
    # platform emits free prose there and nothing in the pipeline reads it, so
    # requiring it would fail a source export for a field we do not use.
    "responses": ["Name", "Timestamp", "City", "Age", "Messages"],
    "meal": ["Name", "Timestamp"],
}
# Accepted sheet names per source. v2 renamed them ('users', 'survey responses');
# the v1 names are kept so archived exports still validate.
_SHEET = {
    "responses": {"users", "mmc bot - responses"},
    "meal": {"survey responses", "mmc-meal"},
}


# Columns that are non-reversible hex digests generated by this pipeline, not
# source text. Hex digits are digits, so a slice will occasionally contain a run
# of 7+ of them and trip the phone-number pattern. Exempting them is safe because
# we generate them; exempting anything else is not. Keep this list closed —
# widening it to a prefix match or a dtype rule would blunt the PII gate.
_HASH_COLUMNS = frozenset({"user_id", "message_id"})


def pii_scan(obj) -> list[dict]:
    """Return violation records for whatsapp:/7+-digit runs. Empty list = clean.

    Skips the columns in `_HASH_COLUMNS` (`user_id`, `message_id`): both are
    non-reversible digests this pipeline computes, and by chance a hex slice can
    contain a 7+-digit run. That is not PII and must not be flagged. Raw Excel
    exports carry neither column, so raw-file scans are unaffected. Also skips
    numeric and boolean dtype columns: they hold metrics, not raw
    phone/`whatsapp:` text, so the scan only covers string/object columns."""
    if isinstance(obj, (str, Path)):
        df = pd.read_excel(obj, header=config.DATA_HEADER_ROW, dtype=str)
    else:
        df = obj
    violations = []
    for col in df.columns:
        if str(col) in _HASH_COLUMNS:
            continue
        # Only string/object columns can hold raw phone numbers or "whatsapp:"
        # runs. Numeric (int/float/bool) columns are legitimate metrics —
        # str()'ing a float routinely produces 7+ consecutive decimal digits
        # (e.g. a ratio like 0.8724100327) that is not PII.
        if pd.api.types.is_numeric_dtype(df[col]) or pd.api.types.is_bool_dtype(df[col]):
            continue
        for val in df[col].astype(str).fillna(""):
            if any(p.search(val) for p in _PII_PATTERNS):
                violations.append({"column": str(col), "value_prefix": val[:12]})
                break  # one hit per column is enough to flag
    return violations


def validate_schema(path, kind: str) -> dict:
    xl = pd.ExcelFile(path)
    names = {str(s).strip().lower() for s in xl.sheet_names}
    if not (names & _SHEET[kind]):
        # tolerate single-sheet test fixtures; only enforce for real exports
        if len(xl.sheet_names) != 1:
            raise ValueError(
                f"expected one of {sorted(_SHEET[kind])} for {kind}, "
                f"got {xl.sheet_names}")
    try:
        # header detected, not assumed — matches the loaders
        df = pd.read_excel(path, header=schema.detect_header_row(path, source=kind))
        df = schema.normalize_columns(df, kind)
    except ValueError:
        # fixture/file too short for the real export's header offset: there is
        # no way the critical columns can be present, so fall through to the
        # missing-columns check below with an empty frame.
        df = pd.DataFrame()
    missing = [c for c in _CRITICAL[kind] if c not in df.columns]
    if missing:
        raise ValueError(f"missing critical columns for {kind}: {missing}")
    ts = df["Timestamp"] if "Timestamp" in df.columns else pd.Series(dtype=object)
    non_null = ts.notna().sum()
    parsed = pd.to_datetime(ts, errors="coerce", utc=True).notna().sum()
    rate = 1.0 if non_null == 0 else parsed / non_null
    return {"rows": len(df), "columns": len(df.columns), "ts_parse_rate": float(rate)}


def reconciliation_table(responses: pd.DataFrame, messages: pd.DataFrame,
                         meal: pd.DataFrame) -> pd.DataFrame:
    n_users = responses["user_id"].nunique()
    n_msgs = len(messages)
    legal = (messages["dominant_category"] == "legal_documentation").mean() if "dominant_category" in messages else float("nan")
    # repeat-asker proxy: users at/above p90 question volume
    q = responses.groupby("user_id")["n_questions"].max()
    p90 = q.quantile(0.90)
    repeat_pct = round(100 * (q >= p90).mean(), 1) if q.notna().any() else "pending"
    rows = [
        ("users", n_users),
        ("records", len(responses)),
        ("messages", n_msgs),
        ("users_with_text", messages["user_id"].nunique()),
        ("meal_responses", len(meal)),
        ("meal_response_rate_pct", round(100 * len(meal) / n_users, 1)),
        ("legal_documentation_pct", round(100 * legal, 1)),
        ("repeat_askers_pct", repeat_pct),
        ("negative_tone_pct", "pending"),  # from NB3 sentiment
    ]
    return pd.DataFrame(rows, columns=["metric", "value"])


def summary_unmappable_share(responses: pd.DataFrame,
                             col: str = "Chat_summary") -> float:
    """Share of non-null summaries that taxonomy.normalize_category cannot map.

    This measures what actually matters: a summary we hold but cannot turn into
    a category. The underlying cause (format change, taxonomy gap, etc.) is
    diagnosed separately. Returns 0.0 if the column is absent or all-null.
    """
    if col not in responses.columns:
        return 0.0
    values = responses[col].dropna()
    if values.empty:
        return 0.0
    unmappable = values.apply(lambda v: taxonomy.normalize_category(v) == "unclassified")
    return float(unmappable.mean())


def _count_prose_share(responses: pd.DataFrame,
                       col: str = "Chat_summary") -> float:
    """Share of non-null summaries in v2 timestamped-prose format.

    Reported on every run so the migration is visible, but NOT itself a failure
    condition — see labelled_unmappable_share.
    """
    if col not in responses.columns:
        return 0.0
    values = responses[col].dropna()
    if values.empty:
        return 0.0
    prose = values.astype(str).str.match(_SUMMARY_PROSE)
    return float(prose.mean())


def labelled_unmappable_share(responses: pd.DataFrame,
                              col: str = "Chat_summary") -> float:
    """Share of *label-shaped* summaries the taxonomy cannot place.

    Timestamped-prose summaries are excluded from both numerator and
    denominator. From the July 2026 platform change onward the summary field is
    free prose carrying no category at all, and those records go to the
    'Suggestion' bucket by design (checkpoint 2026-07-28) — so a growing prose
    share is the expected new normal, not a regression, and gating on it would
    fail every future run.

    What this still catches is the thing that would actually be a bug: a summary
    that LOOKS like a v1 taxonomy label but no longer maps, i.e. the platform
    renamed a category or the taxonomy drifted. Returns 0.0 when there are no
    label-shaped summaries left to check.
    """
    if col not in responses.columns:
        return 0.0
    values = responses[col].dropna().astype(str)
    labelled = values[~values.str.match(_SUMMARY_PROSE)]
    if labelled.empty:
        return 0.0
    unmappable = labelled.apply(
        lambda v: taxonomy.normalize_category(v) == "unclassified")
    return float(unmappable.mean())


def run_checks(responses, messages, meal) -> list[tuple[str, bool, str]]:
    # Second element is always a plain Python bool (not numpy.bool_) so run_meta
    # stays JSON-serializable when a later task persists it.
    checks = []
    checks.append(("P1_pii_responses", bool(pii_scan(responses) == []), "no whatsapp/phone in responses"))
    checks.append(("P1_pii_messages", bool(pii_scan(messages) == []), "no whatsapp/phone in messages"))
    per_user = messages.groupby("user_id")["n_msgs_user"].first().sum()
    checks.append(("P6_spine_invariant", bool(per_user == len(messages)), f"{per_user} == {len(messages)}"))
    checks.append(("P8_meal_unique", bool(meal["user_id"].is_unique), "one MEAL row per user"))
    # P7 asks one question: of the summaries we HOLD, how many can the taxonomy
    # place? Records with no summary at all (306 of 1460 in the 28-Jul export —
    # users who registered but never chatted) are not a taxonomy failure, and
    # counting them put the gate at 22.6% against a 10% limit. They are reported
    # alongside so a jump in silent registrations is still visible.
    # Column-absence tolerant, like every other helper here: a caller passing a
    # hand-built frame gets a vacuous pass, not a KeyError.
    has_summary = (responses["Chat_summary"].notna() if "Chat_summary" in responses
                   else pd.Series(True, index=responses.index))
    n_summary = int(has_summary.sum())
    unclass = float(
        (responses.loc[has_summary, "dominant_category"] == "unclassified").mean()
    ) if n_summary else 0.0
    no_summary = float((~has_summary).mean())
    checks.append((
        "P7_unclassified_share",
        bool(unclass < 0.10),
        f"{unclass:.1%} of {n_summary} summaries unclassified "
        f"({no_summary:.1%} of records carry no summary at all)"))
    labelled_unmappable = labelled_unmappable_share(responses)
    prose = _count_prose_share(responses)
    overall = summary_unmappable_share(responses)
    msg = (
        f"{labelled_unmappable:.1%} of label-shaped summaries cannot be mapped "
        f"(limit {SUMMARY_PROSE_THRESHOLD:.0%}); {prose:.1%} are v2 timestamped prose "
        f"(expected — those go to the 'Suggestion' bucket); {overall:.1%} unmappable "
        f"overall. Remedy: if a v1 category label stopped mapping, extend the "
        f"taxonomy in src/sami/taxonomy.py.")
    checks.append((
        "P9_summary_format",
        bool(labelled_unmappable <= SUMMARY_PROSE_THRESHOLD),
        msg))
    return checks
